# Generated by Django 3.2.9 on 2021-11-29 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visu_type', models.CharField(max_length=200)),
                ('visu_zone', models.CharField(max_length=200)),
                ('visu_dataset', models.CharField(max_length=200)),
                ('visu_title', models.CharField(max_length=200)),
                ('visu_label', models.CharField(choices=[('READMITTED', 'readmitted'), ('A1CRESULT', 'A1Cresult')], default='READMITTED', max_length=30)),
                ('visu_values', models.CharField(choices=[('TIME_IN_HOSPITAL', 'time_in_hospital'), ('NUMBER_OF_MEDICATION', 'number_of_medication')], default='TIME_IN_HOSPITAL', max_length=50)),
            ],
        ),
    ]
