# Generated by Django 3.2.9 on 2021-12-06 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0002_auto_20211206_0851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visu',
            name='visu_dataset',
        ),
        migrations.AlterField(
            model_name='visu',
            name='visu_zone',
            field=models.CharField(choices=[('INFO', 'info'), ('COMPRENDRE', 'comprendre'), ('IMPACT', 'impact')], default='INFO', max_length=30),
        ),
    ]
