# Generated by Django 3.2.9 on 2021-12-06 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0004_alter_visu_visu_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visu',
            name='visu_label',
            field=models.CharField(choices=[('age', 'age'), ('time_in_hospital', 'time_in_hospital'), ('readmitted', 'readmitted'), ('A1Cresult', 'A1Cresult'), ('diabetesMed', 'diabetesMed')], default='READMITTED', max_length=30),
        ),
        migrations.AlterField(
            model_name='visu',
            name='visu_values',
            field=models.CharField(choices=[('COUNT', 'count'), ('time_in_hospital', 'time_in_hospital'), ('number_of_medication', 'number_of_medication')], default='COUNT', max_length=50),
        ),
    ]
