# Generated by Django 3.2.9 on 2021-12-06 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0005_auto_20211206_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='visu',
            name='visu_description',
            field=models.TextField(default='---'),
        ),
        migrations.AddField(
            model_name='visu',
            name='visu_label_title',
            field=models.CharField(default='---', max_length=200),
        ),
    ]
