# Generated by Django 3.2.9 on 2021-12-09 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0007_alter_visu_visu_values'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visu',
            name='visu_values',
            field=models.CharField(choices=[('COUNT', 'count'), ('readmitted', 'readmitted'), ('OTHER', 'other')], default='COUNT', max_length=50),
        ),
    ]
