# Generated by Django 3.2.9 on 2021-12-09 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0013_auto_20211209_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pred',
            name='gender',
            field=models.IntegerField(choices=[(0, 'female'), (1, 'male'), (2, 'unknown')], default=2),
        ),
    ]
