# Generated by Django 3.2.9 on 2021-12-09 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0015_auto_20211209_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pred',
            name='medication',
            field=models.IntegerField(choices=[(0, 'metformin_Down'), (1, 'metformin_No'), (2, 'metformin_Steady'), (3, 'metformin_Up'), (4, 'repaglinide_Down'), (5, 'repaglinide_No'), (6, 'repaglinide_Steady'), (7, 'repaglinide_Up'), (8, 'nateglinide_Down'), (9, 'nateglinide_No'), (10, 'nateglinide_Steady'), (11, 'nateglinide_Up'), (12, 'chlorpropamide_Down'), (13, 'chlorpropamide_No'), (14, 'chlorpropamide_Steady'), (15, 'chlorpropamide_Up'), (16, 'glimepiride_Down'), (17, 'glimepiride_No'), (18, 'glimepiride_Steady'), (19, 'glimepiride_Up'), (20, 'acetohexamide_No'), (21, 'acetohexamide_Steady'), (22, 'glipizide_Down'), (23, 'glipizide_No'), (24, 'glipizide_Steady'), (25, 'glipizide_Up'), (26, 'glyburide_Down'), (27, 'glyburide_No'), (28, 'glyburide_Steady'), (29, 'glyburide_Up'), (30, 'tolbutamide_No'), (31, 'tolbutamide_Steady'), (32, 'pioglitazone_Down'), (33, 'pioglitazone_No'), (34, 'pioglitazone_Steady'), (35, 'pioglitazone_Up'), (36, 'rosiglitazone_Down'), (37, 'rosiglitazone_No'), (38, 'rosiglitazone_Steady'), (39, 'rosiglitazone_Up'), (40, 'acarbose_No'), (41, 'acarbose_Steady'), (42, 'acarbose_Up'), (43, 'miglitol_Down'), (44, 'miglitol_No'), (45, 'miglitol_Steady'), (46, 'miglitol_Up'), (47, 'troglitazone_No'), (48, 'troglitazone_Steady'), (49, 'tolazamide_No'), (50, 'tolazamide_Steady'), (51, 'insulin_Down'), (52, 'insulin_No'), (53, 'insulin_Steady'), (54, 'insulin_Up'), (55, 'glyburide-metformin_Down'), (56, 'glyburide-metformin_No'), (57, 'glyburide-metformin_Steady'), (58, 'glyburide-metformin_Up'), (59, 'glipizide-metformin_No'), (60, 'glipizide-metformin_Steady'), (61, 'glimepiride-pioglitazone_No'), (62, 'metformin-rosiglitazone_No'), (63, 'metformin-rosiglitazone_Steady'), (64, 'metformin-pioglitazone_No'), (65, 'metformin-pioglitazone_Steady')], default=54),
        ),
    ]
