# Generated by Django 3.2.9 on 2021-12-10 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0018_auto_20211209_2255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pred',
            name='medication',
        ),
        migrations.AddField(
            model_name='pred',
            name='acarbose',
            field=models.IntegerField(choices=[(40, 'acarbose_No'), (41, 'acarbose_Steady'), (42, 'acarbose_Up')], default=40),
        ),
        migrations.AddField(
            model_name='pred',
            name='acetohexamide',
            field=models.IntegerField(choices=[(20, 'acetohexamide_No'), (21, 'acetohexamide_Steady')], default=20),
        ),
        migrations.AddField(
            model_name='pred',
            name='chlorpropadine',
            field=models.IntegerField(choices=[(12, 'chlorpropamide_Down'), (13, 'chlorpropamide_No'), (14, 'chlorpropamide_Steady'), (15, 'chlorpropamide_Up')], default=12),
        ),
        migrations.AddField(
            model_name='pred',
            name='glim_pio',
            field=models.IntegerField(choices=[(61, 'glimepiride-pioglitazone_No'), (61, 'NULL')], default=61),
        ),
        migrations.AddField(
            model_name='pred',
            name='glimepiride',
            field=models.IntegerField(choices=[(16, 'glimepiride_Down'), (17, 'glimepiride_No'), (18, 'glimepiride_Steady'), (19, 'glimepiride_Up')], default=16),
        ),
        migrations.AddField(
            model_name='pred',
            name='glizipide',
            field=models.IntegerField(choices=[(22, 'glipizide_Down'), (23, 'glipizide_No'), (24, 'glipizide_Steady'), (25, 'glipizide_Up')], default=22),
        ),
        migrations.AddField(
            model_name='pred',
            name='glybu_met',
            field=models.IntegerField(choices=[(55, 'glyburide-metformin_Down'), (56, 'glyburide-metformin_No'), (57, 'glyburide-metformin_Steady'), (58, 'glyburide-metformin_Up')], default=55),
        ),
        migrations.AddField(
            model_name='pred',
            name='glyburide',
            field=models.IntegerField(choices=[(26, 'glyburide_Down'), (27, 'glyburide_No'), (28, 'glyburide_Steady'), (29, 'glyburide_Up')], default=26),
        ),
        migrations.AddField(
            model_name='pred',
            name='glypy_met',
            field=models.IntegerField(choices=[(59, 'glipizide-metformin_No'), (60, 'glipizide-metformin_Steady')], default=59),
        ),
        migrations.AddField(
            model_name='pred',
            name='insulin',
            field=models.IntegerField(choices=[(51, 'insulin_Down'), (52, 'insulin_No'), (53, 'insulin_Steady'), (54, 'insulin_Up')], default=51),
        ),
        migrations.AddField(
            model_name='pred',
            name='met_pio',
            field=models.IntegerField(choices=[(64, 'metformin-pioglitazone_No'), (65, 'metformin-pioglitazone_Steady')], default=64),
        ),
        migrations.AddField(
            model_name='pred',
            name='met_ros',
            field=models.IntegerField(choices=[(62, 'metformin-rosiglitazone_No'), (63, 'metformin-rosiglitazone_Steady')], default=62),
        ),
        migrations.AddField(
            model_name='pred',
            name='metformin',
            field=models.IntegerField(choices=[(0, 'metformin_Down'), (1, 'metformin_No'), (2, 'metformin_Steady'), (3, 'metformin_Up')], default=0),
        ),
        migrations.AddField(
            model_name='pred',
            name='miglitol',
            field=models.IntegerField(choices=[(43, 'miglitol_Down'), (44, 'miglitol_No'), (45, 'miglitol_Steady'), (46, 'miglitol_Up')], default=43),
        ),
        migrations.AddField(
            model_name='pred',
            name='nateglidine',
            field=models.IntegerField(choices=[(8, 'nateglinide_Down'), (9, 'nateglinide_No'), (10, 'nateglinide_Steady'), (11, 'nateglinide_Up')], default=8),
        ),
        migrations.AddField(
            model_name='pred',
            name='pioglitazone',
            field=models.IntegerField(choices=[(32, 'pioglitazone_Down'), (33, 'pioglitazone_No'), (34, 'pioglitazone_Steady'), (35, 'pioglitazone_Up')], default=32),
        ),
        migrations.AddField(
            model_name='pred',
            name='repaglidine',
            field=models.IntegerField(choices=[(4, 'repaglinide_Down'), (5, 'repaglinide_No'), (6, 'repaglinide_Steady'), (7, 'repaglinide_Up')], default=4),
        ),
        migrations.AddField(
            model_name='pred',
            name='rosiglitazone',
            field=models.IntegerField(choices=[(36, 'rosiglitazone_Down'), (37, 'rosiglitazone_No'), (38, 'rosiglitazone_Steady'), (39, 'rosiglitazone_Up')], default=36),
        ),
        migrations.AddField(
            model_name='pred',
            name='tolazamide',
            field=models.IntegerField(choices=[(49, 'tolazamide_No'), (50, 'tolazamide_Steady')], default=49),
        ),
        migrations.AddField(
            model_name='pred',
            name='tolbutamide',
            field=models.IntegerField(choices=[(30, 'tolbutamide_No'), (31, 'tolbutamide_Steady')], default=30),
        ),
        migrations.AddField(
            model_name='pred',
            name='troglitazone',
            field=models.IntegerField(choices=[(47, 'troglitazone_No'), (48, 'troglitazone_Steady')], default=47),
        ),
    ]
